"""gorevlere iptal durumu ekle

Revision ID: 48862aeb2649
Revises: 470e911c7b97
Create Date: 2026-09-24 12:10:20.977588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48862aeb2649'
down_revision: Union[str, Sequence[str], None] = '470e911c7b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cancelled_at')
    # ### end Alembic commands ###
