"""baseline mevcut sema

Revision ID: 55b5004dec18
Revises: 
Create Date: 2026-09-23 17:47:42.332557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b5004dec18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), server_default=sa.text("('')"), nullable=False),
    sa.Column('address', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('tax_info', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('phone', sa.String(length=50), server_default=sa.text("('')"), nullable=False),
    sa.Column('email', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('website', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('bank_info', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('quote_prefix', sa.String(length=10), server_default=sa.text("'OZ'"), nullable=False),
    sa.Column('quote_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('po_prefix', sa.String(length=10), server_default=sa.text("'P'"), nullable=False),
    sa.Column('po_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shipment_prefix', sa.String(length=10), server_default=sa.text("'CRG'"), nullable=False),
    sa.Column('shipment_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivery_prefix', sa.String(length=10), server_default=sa.text("'OUT'"), nullable=False),
    sa.Column('delivery_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tax_no', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('req_seq', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name'),
    sa.UniqueConstraint('company_id', 'short_code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('spec', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.String(length=30), nullable=False),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('last_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), server_default=sa.text("'Gümrük Teslim'"), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('logistics_margin_pct', sa.Float(), nullable=True),
    sa.Column('tax_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('tax_pct', sa.Float(), nullable=False),
    sa.Column('logistics_mode', sa.String(length=10), server_default=sa.text("'dahil'"), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=False),
    sa.Column('quote_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('shelved_reason', sa.Text(), nullable=False),
    sa.Column('po_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('po_number', sa.String(length=60), nullable=True),
    sa.Column('customer_po_no', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index('ix_reqs_stage', 'reqs', ['company_id', 'stage'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('awb_no', sa.String(length=60), server_default=sa.text("('')"), nullable=False),
    sa.Column('carrier', sa.String(length=60), server_default=sa.text("('')"), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logistics_status', sa.String(length=60), server_default=sa.text("'Çıkış Hazırlığında'"), nullable=False),
    sa.Column('customs_status', sa.String(length=60), server_default=sa.text("'Bekliyor'"), nullable=False),
    sa.Column('gcb_no', sa.String(length=60), server_default=sa.text("('')"), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), server_default=sa.text("'Belirtilmedi'"), nullable=False),
    sa.Column('delivery_address', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('current_location', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('last_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), server_default=sa.text("'diger'"), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), server_default=sa.text("('')"), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_shipment_id'), 'attachments', ['shipment_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('delivered_by', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('delivered_to', sa.String(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number')
    )
    op.create_index(op.f('ix_deliveries_req_id'), 'deliveries', ['req_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=True),
    sa.Column('to_stage', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_req_id'), 'events', ['req_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number')
    )
    op.create_index(op.f('ix_quotes_req_id'), 'quotes', ['req_id'], unique=False)
    op.create_table('req_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default=sa.text("'diger'"), nullable=False),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('req_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('unit_customs', sa.Float(), nullable=True),
    sa.Column('unit_logistics', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('sale_price_override', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('req_line_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['req_line_id'], ['req_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('req_line_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['req_id'], ['reqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['req_line_id'], ['req_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_items')
    op.drop_table('delivery_lines')
    op.drop_table('req_lines')
    op.drop_table('req_costs')
    op.drop_index(op.f('ix_quotes_req_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_events_req_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deliveries_req_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_attachments_shipment_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('shipments')
    op.drop_index('ix_reqs_stage', table_name='reqs')
    op.drop_table('reqs')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('partners')
    op.drop_table('companies')
    # ### end Alembic commands ###
